package httpapi

import "net/http"

func (s *Server) routes() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", s.handleHealth)
	mux.HandleFunc("GET /api/version", s.handleVersion)
	mux.HandleFunc("GET /api/events", s.handleListEvents)
	mux.HandleFunc("POST /api/events/import", s.handleImportEvent)
	mux.HandleFunc("POST /api/events/{id}/rfid-import", s.handleRfidImport)
	mux.HandleFunc("POST /api/events/{id}/recount", s.handleRecount)
	mux.HandleFunc("GET /api/events/{id}/races", s.handleListRaces)
	mux.HandleFunc("GET /api/events/{id}/races/{raceID}/protocol", s.handleProtocol)
	mux.HandleFunc("GET /api/events/{id}/races/{raceID}/protocol.xlsx", s.handleProtocolXLSX)
	mux.HandleFunc("POST /api/events/{id}/races/{raceID}/export-xlsx", s.handleExportXLSX)
	mux.HandleFunc("POST /api/events/{id}/edits", s.handleApplyEdit)
	mux.HandleFunc("GET /api/events/{id}/edits", s.handleListEdits)
	mux.HandleFunc("GET /api/events/{id}/checkpoints", s.handleListCheckpoints)
	mux.HandleFunc("GET /api/events/{id}/members/{memberID}/passes", s.handleMemberPasses)
	mux.HandleFunc("POST /api/events/{id}/members", s.handleCreateMember)
	mux.HandleFunc("GET /api/events/{id}/members/{memberID}", s.handleGetMember)
	mux.HandleFunc("GET /api/events/{id}/categories", s.handleListCategories)
	mux.HandleFunc("GET /api/events/{id}/races/{raceID}/categories", s.handleListRaceCategories)
	mux.HandleFunc("POST /api/events/{id}/races/{raceID}/categories", s.handleAttachCategory)
	mux.HandleFunc("DELETE /api/events/{id}/races/{raceID}/categories/{categoryID}", s.handleDetachCategory)
	mux.HandleFunc("GET /api/events/{id}/members", s.handleListMembers)
	mux.HandleFunc("POST /api/events/{id}/checkpoints", s.handleCreateCheckpoint)
	mux.HandleFunc("DELETE /api/events/{id}/checkpoints/{cpID}", s.handleDeleteCheckpoint)
	mux.HandleFunc("POST /api/events/{id}/backup", s.handleBackup)
	mux.HandleFunc("POST /api/events/{id}/export-json", s.handleExportJSON)
	mux.HandleFunc("POST /api/events/{id}/live/start", s.handleLiveStart)
	mux.HandleFunc("POST /api/events/{id}/live/stop", s.handleLiveStop)
	mux.HandleFunc("GET /api/events/{id}/live/status", s.handleLiveStatus)
	mux.HandleFunc("GET /api/events/{id}/live/feed", s.handleLiveFeed)
	mux.HandleFunc("POST /api/events/{id}/members/{memberID}/manual-finish", s.handleManualFinish)
	mux.HandleFunc("GET /api/events/{id}/manual-results", s.handleListManualResults)
	mux.HandleFunc("DELETE /api/events/{id}/results/{resultID}", s.handleDeleteManualResult)
	mux.HandleFunc("POST /api/events/{id}/captures", s.handleCreateCapture)
	mux.HandleFunc("GET /api/events/{id}/captures", s.handleListCaptures)
	mux.HandleFunc("DELETE /api/events/{id}/captures/{capID}", s.handleDeleteCapture)
	mux.HandleFunc("GET /api/events/{id}/photos/sources", s.handleListPhotoSources)
	mux.HandleFunc("POST /api/events/{id}/photos/sources", s.handleAddPhotoSource)
	mux.HandleFunc("DELETE /api/events/{id}/photos/sources", s.handleDeletePhotoSource)
	mux.HandleFunc("POST /api/events/{id}/photos/poll", s.handlePollPhotos)
	mux.HandleFunc("GET /api/events/{id}/photos/status", s.handlePhotoStatus)
	mux.HandleFunc("GET /api/events/{id}/photos/recent", s.handleRecentPhotos)
	mux.HandleFunc("GET /api/events/{id}/photos/merged", s.handleMergedPhotos)
	mux.HandleFunc("POST /api/events/{id}/photos/export", s.handleExportFinishes)
	mux.HandleFunc("GET /api/events/{id}/photos/img", s.handlePhotoImage)
	mux.HandleFunc("GET /api/events/{id}/photos", s.handleMatchPhotos)
	mux.HandleFunc("POST /api/public/start", s.handlePublicStart)
	mux.HandleFunc("POST /api/public/stop", s.handlePublicStop)
	mux.HandleFunc("GET /api/public/status", s.handlePublicStatus)
	mux.HandleFunc("GET /api/events/{id}/sync-config", s.handleGetSyncConfig)
	mux.HandleFunc("PUT /api/events/{id}/sync-config", s.handleSetSyncConfig)
	mux.HandleFunc("POST /api/events/{id}/sync", s.handleSyncPush)
	mux.HandleFunc("POST /api/events/{id}/sync-pull", s.handleSyncPull)
	return mux
}
