// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIBaseURL() {
  return window['go']['main']['App']['APIBaseURL']();
}

export function APIToken() {
  return window['go']['main']['App']['APIToken']();
}
